on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: donPain/ActionMobral@0.0
        with:
          who-to-greet: 'Olá eduardo'
    
